### ISSUE TITLE
Eruda requires lax Content Security Policy (CSP)

### ISSUE THREAD

**Issue by steffenweber** [liriliri/eruda#13]
Thank you for this nice tool!

I'm using a [Content Security Policy (CSP)](http://www.html5rocks.com/en/tutorials/security/content-security-policy/) as defense in depth against [Cross-site scripting (XSS)](https://en.wikipedia.org/wiki/Cross-site_scripting) security vulnerabilities. Eruda currently requires the following CSP:

```
Content-Security-Policy: script-src https://liriliri.github.io/eruda/eruda.min.js 'unsafe-inline'; font-src data:
```

I'd like to get rid of the `unsafe-inline` directive. Eruda seems to be working fine without this directive but the Chrome Developer Tools Console logs errors:

> Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src https://liriliri.github.io/eruda/eruda.min.js". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

This seems to be triggered by "ontouchstart" attributes which exists on multiple elements injected by Eruda ([example](https://github.com/liriliri/eruda/blob/f96149929559df23874f7a2ec72fb11606fdc318/src/EntryBtn/EntryBtn.hbs#L1)). These attributes don't have a value. What is their purpose? Can they be removed?

**Comment by surunzi** [comment]
The "ontouchstart" attribute is used to solve the [ios css :active style issue](http://stackoverflow.com/questions/3885018/active-pseudo-class-doesnt-work-in-mobile-safari). Not planning to remove it because I was unable to find any other useful way.

Can you download the js file on your domain to solve the CSP issue? `npm install eruda` or [jsdelivr](http://www.jsdelivr.com/projects/eruda). Plus, it's not recommended to use the demo page's script since it's being updated frequently and maybe buggy sometimes.

**Comment by surunzi** [comment]
Not familiar with CSP. To me, using `ontouchstart` is the best way to solve the style issue for now. And when the issue is fixed on ios, if ever, it will be very easy to remove all the `ontouchstart>` text. 

Maybe replacing all `ontouchstart>` to `>` manually will do the trick for your situation?

**Comment by steffenweber** [comment]
I'm totally fine with not fixing this issue at the moment. :smiley:

(Yes, I'm thinking about removing the `ontouchstart` workaround in my local copy since I primarily use Android.)

**Comment by difhel** [comment]
Can this be reopened?
