### ISSUE TITLE
Not working on discord site why ??😡🤬

### ISSUE THREAD

**Issue by ScripterSaurav** [liriliri/eruda#204]
I have tried to use Inspect Element on discord.com site but it's not showing floating element tool on that site . i have tried this again on another site vedantu.com it's worked but not worked on discord.com site why ? fix it soon 😡

**Comment by SparshaDhar** [comment]
Because loading external scripts are blocked in many sites for Security reasons.

But first of all, I would request you to be respectful to the Authors of this free open-source project and any other projects especially those which are maintained for free by some awesome people. Programmers often work without a salary to make a proper living, just for the sake of passion. Hoping you understand this. Thanks.
