### ISSUE TITLE
Can we use this on any page from a mobile device?

### ISSUE THREAD

**Issue by julkhami** [liriliri/eruda#215]
I wanted to inspect a certain web page for a certain authorisation token, on my phone. Is this possible with Eruda or is it just for web pages you are an author of yourself so you can put the JavaScript lines in?

**Comment by Madghostek** [comment]
I was able to run it on chrome for android with this small script `javascript:(function(){ let s = document.createElement('script'); s.src="//cdn.jsdelivr.net/npm/eruda"; document.body.appendChild(s);script.onload = function() { eruda.init() } })();` (you paste this to url bar)
Firefox doesn't execute it but tries googling instead 😑 probably because it contains spaces, but even without them the javascript: prefix doesnt seem to work on firefox for android, maybe just for me. However there's an addon MobiDevTools which implements this eruda (its possible to use addons on android, there are many articles on google)

**Comment by fzs111** [comment]
If you just paste the link, most browsers will strip the `javascript:` part (as a kind of protection). If you type it back manually, it should work.

If you use this frquently, you can also [create a bookmarklet from it](https://android.stackexchange.com/a/210701/367588).

**Comment by leohku** [comment]
I've made a small script which injects Eruda to websites on Android in the VPN layer, so it works in Chrome, Firefox, or on websites with Content Security Policy set - feel free to check it out here: https://github.com/leohku/andure

**Comment by WebLeach** [comment]
Just use the bookmark trick, works all the way

Make a random bookmark
Paste the script as url on the bookmark, on search bar type the title of that bookmark and HIT IT.

**Comment by qxb3** [comment]
> Just use the bookmark trick, works all the way
> 
> Make a random bookmark Paste the script as url on the bookmark, on search bar type the title of that bookmark and HIT IT.

that is kinda pain in the ass to do everytime tho

**Comment by RaSan147** [comment]
> that is kinda pain in the ass to do everytime tho

Remember: something is better than nothing at all
