### ISSUE TITLE
what is the ID for the little gear icon

### ISSUE THREAD

**Issue by zek-c** [liriliri/eruda#315]
the little gear icon in the corner you click to make it appear what is the ID of it i need it to i can make it so i can press h to make it dissapear on computers

**Comment by SipSup3314** [comment]
use inspect element. do it yourself. stop asking people if you didnt try. jesus helped those who helped themselves. you should learn from him.

**Comment by zek-c** [comment]
whats your problem lmao i was asking because i cant inspect element on my SCHOOL ISSUED chromebok lmao

**Comment by zek-c** [comment]
> use inspect element. do it yourself. stop asking people if you didnt try. jesus helped those who helped themselves. you should learn from him.

you didnt capitalize Jesus either

**Comment by SipSup3314** [comment]
Try a personal device.

**Comment by zek-c** [comment]
i dont even care anymore lmao im working on different things i made my own console like eruda so hush

**Comment by SipSup3314** [comment]
Hello. I am back. I would like to apologize. It was very late at night when i wrote those previous messages and i was running low on sanity and common sense. What i said was rude, because i gave no idea what's going on in your life. You may not have access to some things because of schools. You might even be homeless or something. Who knows? It was very rude and I am sorry about that.
